// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdlnjlhzqqmvuvysqlqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkbG5qbGh6cXFtdnV2eXNxbHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTAzMjYsImV4cCI6MjA3NDk2NjMyNn0.e9bHWU30cajRrt45GIfZD739txyZedJW5Vn6hEW_q4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});